version: "3.8"

services:
  postgres:
    container_name: prisma_db
    image: postgres:alpine3.18
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root_123
      - POSTGRES_DB=prisma_db
      - PGDATA=/data/postgres
      - TZ=Europe/Istanbul
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
